#+title: Unofficial ELPA Mirror

This ELPA mirror includes all of the widely used ELPAs and is automatically
synchronized once a day via efficient rsync by the [[https://github.com/emacs-elpa/mirror/blob/main/sync.sh][sync.sh]] shell script. For
each package devel and stable versions are provided. The mirror is small since
only the latest tarball of each published package is kept. As shallow clone, the
.git directory has a size below 1 GiB. The uncompressed package tarballs in
[[https://github.com/emacs-elpa/mirror/tree/main/devel][devel/]] and [[https://github.com/emacs-elpa/mirror/tree/main/stable][stable/]] have a size of around 2.2 GiB.

* Devel

The devel archives can be configured as follows:

#+begin_src emacs-lisp
(setq package-archives '(("gnu-devel"    . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/devel/gnu/")
                         ("nongnu-devel" . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/devel/nongnu/")
                         ("melpa-devel"  . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/devel/melpa/"))
      package-archive-priorities '(("gnu-devel"    . 2)
                                   ("nongnu-devel" . 1)
                                   ("melpa-devel"  . 0))
      package-archive-column-width 14
      package-version-column-width 26
      package-review-policy t
      package-list-unsigned t)
#+end_src

* Stable

The stable archives can be configured as follows:

#+begin_src emacs-lisp
(setq package-archives '(("gnu-stable"    . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/stable/gnu/")
                         ("nongnu-stable" . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/stable/nongnu/")
                         ("melpa-stable"  . "https://raw.githubusercontent.com/emacs-elpa/mirror/main/stable/melpa/"))
      package-archive-priorities '(("gnu-stable"    . 2)
                                   ("nongnu-stable" . 1)
                                   ("melpa-stable"  . 0))
      package-archive-column-width 14
      package-version-column-width 26
      package-review-policy t
      package-list-unsigned t)
#+end_src

* Daily snapshots

For every daily synchronization a git tag ~%Y-%m-%d~ is created. One can access
the daily snapshots of all archives as follows, for instance for the date
~2026-06-26~:

#+begin_src emacs-lisp
(setq package-archives '(("gnu-devel"    . "https://raw.githubusercontent.com/emacs-elpa/mirror/refs/tags/2026-06-26/devel/gnu/")
                         ("nongnu-devel" . "https://raw.githubusercontent.com/emacs-elpa/mirror/refs/tags/2026-06-26/devel/nongnu/")
                         ("melpa-devel"  . "https://raw.githubusercontent.com/emacs-elpa/mirror/refs/tags/2026-06-26/devel/melpa/"))
      package-archive-priorities '(("gnu-devel"    . 2)
                                   ("nongnu-devel" . 1)
                                   ("melpa-devel"  . 0))
      package-archive-column-width 14
      package-version-column-width 26
      package-review-policy t
      package-list-unsigned t)
#+end_src

* Other mirrors and scripts

Here you find other mirrors and scripts.

- https://github.com/d12frosted/elpa-mirror
- https://github.com/d12frosted/mirror-elpa
- https://github.com/delpa-org
- https://github.com/elpa-mirrors
- https://github.com/emacs-straight
- https://github.com/emacsmirror
- https://github.com/redguardtoo/elpa-mirror
